//! Type-run maps for MC02 chunk payloads, embedded from
//! `scripts/python/nfssave/typemaps.json` (generated by `docs/re/typemap.py`
//! from matched 360/PC sample pairs).
//!
//! Each entry maps a chunk id (hex key in the JSON) to its reference payload
//! size and a list of `[start, end, class]` runs (`S32` = u32-swapped,
//! `S16` = u16-swapped, `NAT` = natural byte order). The 360->PC conversion
//! pipeline uses the fieldmaps (see [`crate::payload_rules`]); the typemaps
//! are reference data for analysis tooling, embedded so the Rust tree carries
//! the same resources as the Python package.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

const TYPEMAPS_JSON: &str = include_str!("../../../../scripts/python/nfssave/typemaps.json");

/// One typed run: `[start, end, class]` (`S32`/`S16`/`NAT`).
pub type TypeRun = (u64, u64, String);

#[derive(Debug, Clone, Deserialize)]
pub struct TypeRuns {
    pub size: u64,
    pub runs: Vec<TypeRun>,
}

static MAPS: OnceLock<HashMap<u32, TypeRuns>> = OnceLock::new();

/// Chunk-id-keyed type-run table (hex ids in the JSON, e.g. "3B309E09").
pub fn typemaps() -> &'static HashMap<u32, TypeRuns> {
    MAPS.get_or_init(|| {
        let raw: HashMap<String, TypeRuns> =
            serde_json::from_str(TYPEMAPS_JSON).expect("embedded typemaps.json is valid");
        raw.into_iter()
            .map(|(k, v)| (u32::from_str_radix(&k, 16).expect("hex chunk id"), v))
            .collect()
    })
}
